package report

import (
	"io"
	"regexp"
	"sort"
	"strings"

	"github.com/ciruzz00/astro/internal/cases"
	"github.com/ciruzz00/astro/internal/ioc"
)

var reTechnique = regexp.MustCompile(`^T\d{4}(\.\d{3})?$`)

type navTechnique struct {
	TechniqueID string `json:"techniqueID"`
	Score       int    `json:"score"`
	Color       string `json:"color"`
	Comment     string `json:"comment,omitempty"`
	Enabled     bool   `json:"enabled"`
}

// Scores and colors of the layer: techniques added to the case explicitly
// rank above those only referenced by threat intel about its indicators.
const (
	scoreDirect     = 2
	scoreReferenced = 1
	colorDirect     = "#e60d0d"
	colorReferenced = "#ff9f43"
)

// Navigator writes a MITRE ATT&CK Navigator layer (enterprise) highlighting
// the case techniques and those referenced in its OTX results.
func Navigator(w io.Writer, v *cases.View, o Options) error {
	techs := map[string]*navTechnique{}
	add := func(id string, score int, color, source string) {
		id = strings.ToUpper(id)
		if !reTechnique.MatchString(id) {
			return
		}
		t, ok := techs[id]
		if !ok {
			t = &navTechnique{TechniqueID: id, Enabled: true}
			techs[id] = t
		}
		if score > t.Score {
			t.Score, t.Color = score, color
		}
		if source != "" && !strings.Contains(t.Comment, source) {
			t.Comment = strings.TrimPrefix(t.Comment+"; "+source, "; ")
		}
	}

	for _, it := range v.Items {
		if it.Indicator.Type == ioc.AttackTechnique {
			add(it.Indicator.Value, scoreDirect, colorDirect, "in case")
			continue
		}
		for _, id := range otxTechniques(it) {
			add(id, scoreReferenced, colorReferenced, "OTX: "+ioc.Defang(it.Indicator))
		}
	}

	list := make([]navTechnique, 0, len(techs))
	for _, t := range techs {
		list = append(list, *t)
	}
	sort.Slice(list, func(a, b int) bool { return list[a].TechniqueID < list[b].TechniqueID })

	name := v.Case.Title
	if name == "" {
		name = v.Case.Name
	}
	attackVersion := o.AttackVersion
	if k := strings.Index(attackVersion, "."); k > 0 {
		attackVersion = attackVersion[:k]
	}
	if attackVersion == "" {
		attackVersion = "19"
	}
	layer := map[string]any{
		"name":        name,
		"versions":    map[string]string{"attack": attackVersion, "navigator": "5.1.0", "layer": "4.5"},
		"domain":      "enterprise-attack",
		"description": "astro case " + v.Case.Name + " (TLP:" + v.Case.TLP + ")",
		"techniques":  list,
		"gradient":    map[string]any{"colors": []string{"#ffffff", colorReferenced, colorDirect}, "minValue": 0, "maxValue": scoreDirect},
		"legendItems": []map[string]string{
			{"label": "Technique in the case", "color": colorDirect},
			{"label": "Referenced by threat intel on case indicators", "color": colorReferenced},
		},
		"metadata": []map[string]string{{"name": "TLP", "value": v.Case.TLP}, {"name": "generated by", "value": "astro " + o.Version}},
	}
	return writeJSON(w, layer)
}

// otxTechniques reads ATT&CK IDs from a stored OTX result. Stored reports
// decode provider details as generic JSON maps.
func otxTechniques(it cases.Item) []string {
	if it.Report == nil {
		return nil
	}
	var out []string
	for _, r := range it.Report.Results {
		if r.Provider != "alienvault-otx" {
			continue
		}
		details, _ := r.Details.(map[string]any)
		pulses, _ := details["pulses"].([]any)
		for _, p := range pulses {
			pm, _ := p.(map[string]any)
			ids, _ := pm["attack_ids"].([]any)
			for _, a := range ids {
				if am, ok := a.(map[string]any); ok {
					if id, ok := am["id"].(string); ok {
						out = append(out, id)
					}
				}
			}
		}
	}
	return out
}
